from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
output=r"C:\Users\henri\Documents\Codex\2026-08-13\sites-plugin-sites-openai-bundled-criar\outputs\curriculo-prof-henrique-santos.pdf"
doc=SimpleDocTemplate(output,pagesize=A4,rightMargin=1.75*cm,leftMargin=1.75*cm,topMargin=1.55*cm,bottomMargin=1.5*cm); st=getSampleStyleSheet(); ink=HexColor('#15243d'); blue=HexColor('#1769e8'); green=HexColor('#1d735d'); grey=HexColor('#62738a')
title=ParagraphStyle('title',parent=st['Title'],fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=ink,spaceAfter=4); sub=ParagraphStyle('sub',parent=st['Normal'],fontName='Helvetica-Bold',fontSize=11,leading=15,textColor=blue,spaceAfter=12); body=ParagraphStyle('body',parent=st['Normal'],fontName='Helvetica',fontSize=9.7,leading=14,textColor=ink,spaceAfter=7); muted=ParagraphStyle('muted',parent=body,textColor=grey); sec=ParagraphStyle('sec',parent=st['Heading2'],fontName='Helvetica-Bold',fontSize=11,leading=14,textColor=green,spaceBefore=13,spaceAfter=6); role=ParagraphStyle('role',parent=body,fontName='Helvetica-Bold',fontSize=10.2,leading=14,spaceAfter=1)
s=[Paragraph('Prof. Henrique Santos',title),Paragraph('DESENVOLVEDOR DE SOFTWARE &amp; INSTRUTOR DE TECNOLOGIA',sub),Paragraph('GitHub: github.com/HenriqueSanttos  |  LinkedIn: linkedin.com/in/henrique-santos19/',muted),Paragraph('PERFIL PROFISSIONAL',sec),Paragraph('Bacharel em Agrocomputação (2021), com experiência entre tecnologia aplicada e educação profissional. Atua no desenvolvimento de aplicações escaláveis com Flutter, Dart e Node.js, além da criação de materiais didáticos e projetos maker de código aberto. Seu foco é tornar a tecnologia acessível, prática e relevante para a sala de aula e o dia a dia.',body),Paragraph('EXPERIÊNCIA',sec),Paragraph('Instrutor de Formação Profissional - SENAI',role),Paragraph('Criação de planos de aula, guias técnicos e instrução de tecnologias industriais e educacionais.',body),Paragraph('Desenvolvimento de Produtos Digitais - Ponto Rápido e Festô',role),Paragraph('Idealização e desenvolvimento ativo de aplicações, incluindo arquitetura em Flutter, modelagem de dados e estruturação de plataformas.',body),Paragraph('Analista de Implantação de Projetos - Solinftec',role),Paragraph('Experiência corporativa com implantação de tecnologia de ponta e suporte à adoção de soluções no contexto aplicado.',body),Paragraph('FORMAÇÃO',sec),Paragraph('Bacharelado em Agrocomputação - 2021',role),Paragraph('COMPETÊNCIAS',sec)]
d=[[Paragraph('<b>Desenvolvimento</b><br/>Flutter, Dart, Node.js, arquitetura de aplicações e modelagem de banco de dados.',body),Paragraph('<b>Educação tecnológica</b><br/>Planos de aula, guias técnicos, instrução profissional e materiais didáticos.',body),Paragraph('<b>Cultura maker</b><br/>Arduino, ESP32, sensores capacitivos e projetos open-source de automação didática.',body)]];t=Table(d,colWidths=[5.45*cm]*3);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),HexColor('#f4f8ff')),('BOX',(0,0),(-1,-1),.4,HexColor('#dce6f1')),('INNERGRID',(0,0),(-1,-1),.4,HexColor('#dce6f1')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),10),('RIGHTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),7)]));s+=[t,Paragraph('PROJETOS EM DESTAQUE',sec),Paragraph('<b>Ponto Rápido:</b> aplicativo de gestão corporativa com arquitetura e desenvolvimento em Flutter.<br/><b>Festô:</b> marketplace de eventos, estruturado desde a modelagem de banco de dados.<br/><b>Agro-Hacking:</b> kit educacional aberto de automação agrícola com Arduino, ESP32 e sensores de umidade do solo.',body)];doc.build(s)
